#!/bin/bash
#SBATCH -p ********
#SBATCH --nodes=2
#SBATCH --exclusive
#SBATCH --ntasks-per-node=4
#SBATCH --cpus-per-task=36
#SBATCH --gpus-per-node=4
#SBATCH --time=01:00:00
#SBATCH --job-name=nccl



export NCCL_NVLS_ENABLE=1
export NCCL_DEBUG=INFO
export NCCL_P2P_LEVEL=NVL
export NCCL_CUMEM_ENABLE=1
export NCCL_RUNTIME_CONNECT=0 # Avoid lazy connection overhead when benchmarking 
export NCCL_MNNVL_ENABLE=1

export NCCL_SOCKET_IFNAME=bond0
export UCX_NET_DEVICES=bond0
#optional
############
# export NCCL_MIN_CTAS=16

# export UCX_TLS=rc

# export OMPI_MCA_pml=ucx
# export OMPI_MCA_coll_hcoll_enable=0
# export OMPI_MCA_btl=^openib,smcuda
# export OMPI_MCA_coll=^hcoll
# export OMPI_MCA_btl_openib_if_include=bond0



export NCCL_MNNVL_ENABLE=0
[[ ${SLURM_JOB_NUM_NODES} -gt 1 ]] && { export NCCL_MNNVL_ENABLE=1; }



srun --mpi=pmix --export=ALL --cpu-bind=none --ntasks-per-node=4 \
                --container-image="${IMAGE}" \
                --container-mounts=${MOUNT_DIR}:${MOUNT_DIR} \
		all_reduce_perf_mpi -b 8 -f 2 -g 1 -e 16g | tee ${LOGDIR}/nccl-allreduce_${SLURM_JOB_NUM_NODES}nodes-${SLURM_JOB_NODELIST}_${SLURM_JOB_ID}.log


srun --mpi=pmix --export=ALL --cpu-bind=none --ntasks-per-node=4 \
                --container-image="${IMAGE}" \
                --container-mounts=${MOUNT_DIR}:${MOUNT_DIR} \
		alltoall_perf_mpi -b 8 -f 2 -g 1 -e 16g | tee ${LOGDIR}/nccl-all2all_${SLURM_JOB_NUM_NODES}nodes-${SLURM_JOB_NODELIST}_${SLURM_JOB_ID}.log

srun --mpi=pmix --export=ALL --cpu-bind=none --ntasks-per-node=4 \
                --container-image="${IMAGE}" \
                --container-mounts=${MOUNT_DIR}:${MOUNT_DIR} \
		all_gather_perf_mpi -b 8 -f 2 -g 1 -e 16g | tee ${LOGDIR}/nccl-allgather_${SLURM_JOB_NUM_NODES}nodes-${SLURM_JOB_NODELIST}_${SLURM_JOB_ID}.log
